dependencies {
	compileOnly group: "com.liferay.portal", name: "release.portal.api"

	cssBuilder group: "com.liferay", name: "com.liferay.css.builder", version: "3.1.4"

    testImplementation group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "4.94.0"
	testImplementation 'junit:junit:4.13.2'
	
	implementation project(":modules:register:register-api")
	implementation project(":modules:register:register-service")
}