/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.vass.register.model.impl;

import com.vass.register.model.CustomUser;
import com.vass.register.service.CustomUserLocalServiceUtil;

/**
 * The extended model base implementation for the CustomUser service. Represents a row in the &quot;CUSTOMUSER_CustomUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomUserImpl
 * @see CustomUser
 * @generated
 */
public abstract class CustomUserBaseImpl
	extends CustomUserModelImpl implements CustomUser {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a custom user model instance should use the <code>CustomUser</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CustomUserLocalServiceUtil.addCustomUser(this);
		}
		else {
			CustomUserLocalServiceUtil.updateCustomUser(this);
		}
	}

}