/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.vass.register.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomUser service. Represents a row in the &quot;CUSTOMUSER_CustomUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.vass.register.model.impl.CustomUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.vass.register.model.impl.CustomUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomUser
 * @generated
 */
@ProviderType
public interface CustomUserModel extends BaseModel<CustomUser> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom user model instance should use the {@link CustomUser} interface instead.
	 */

	/**
	 * Returns the primary key of this custom user.
	 *
	 * @return the primary key of this custom user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom user.
	 *
	 * @param primaryKey the primary key of this custom user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this custom user.
	 *
	 * @return the uuid of this custom user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this custom user.
	 *
	 * @param uuid the uuid of this custom user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user ID of this custom user.
	 *
	 * @return the user ID of this custom user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this custom user.
	 *
	 * @param userId the user ID of this custom user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom user.
	 *
	 * @return the user uuid of this custom user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom user.
	 *
	 * @param userUuid the user uuid of this custom user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this custom user.
	 *
	 * @return the name of this custom user
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this custom user.
	 *
	 * @param name the name of this custom user
	 */
	public void setName(String name);

	/**
	 * Returns the email of this custom user.
	 *
	 * @return the email of this custom user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this custom user.
	 *
	 * @param email the email of this custom user
	 */
	public void setEmail(String email);

	@Override
	public CustomUser cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}